### PR TITLE
Big updates

### PR DESCRIPTION
**Pull request by alextd**
Tracks inventory for any bill - meals, drugs, medicine, whatever. Also counts on pack animals! (Issue #31 thoroughly close)

This includes hauling items, so items carried away from a bill are immediately included in the bill count.

Consolidated the options to "Count colonist's items" - apparel, weapon, or whatever - everything on the colonist is checked.

A few fixes:
- Counting installed sculptures, as the base game does. Added an option to turn it off. Of course it counts hauling them as well, now.
- Bills look for items on their map, not the visible one - colony A would start work if colony B has low supplies.
- Fix bills forgetting their stockpiles on load - another map dependency.  (Fixes Issue #29)
- Fix copied bills across maps taking to imaginary zones - where the original bill's zone was, but the wrong map (There still is a problem or two with this, nothing too bad)

### CODE REVIEW

**Comment by Falconne** [comment]
Great stuff. I'll go through it and merge soon. I need to do it manually as I rebased the last pull request.

**Comment by alextd** [comment]
Another thing to note that shouldn't be forgotten:

Translations. I don't know the process, so I don't know if I messed up the process, but I temporarily slotted in the translation for "Count worn apparel" into "Count colonist's items" and that should get re-translated. Perhaps translators won't see it missing, and it should be cleared, or if you tell them, whatever, that needs to be done.

**Comment by alextd** [comment]
Oh snap, new commits got stuck into the pull request.

Well - now it can track colonists away on a caravan. (#38)

The UI had to be adjusted up a bit, since clothes have 4 options now. I don't think that'll be a problem - unless you know of a bill that takes up a lot of space on the left column.

**Comment by alextd** [comment]
Being ever vigilant - a fix where my changes overcounted resources.

**Comment by Falconne** [comment]
I haven't had a chance to go through all the code yet, but from the comments it looks like the item counter now counts items in other colonies too? If so, that should probably be controlled by a mod level setting? Like "Count Items in Whole World". Because not everyone's workflow would want that. That option could cover counting items on travelling caravans too.

**Comment by alextd** [comment]
Counting elsewhere is a bill option just like the rest: ShouldCheckAway,  _extendedBillData.CountAway

**Comment by Falconne** [comment]
Sorry, yeah I misread the comment. I wonder if counting items on travelling caravans should be a mod level option that applies to all bills? Or would the use cases for that generally be on specific items?

**Comment by alextd** [comment]
Yea, I figured my armor and weapons would count, since they're on the pawns coming back. My apparel that I create sell for profit isn't coming back

**Comment by alextd** [comment]
Also note it only counts caravans sent from that colony, and doesn't count people in other colonies at all

**Comment by Falconne** [comment]
Oh yeah good point.

By the way can you try rebasing you branch against my `master`? It would fix the auto merge conflict. It might be worth creating a new branch called `develop` off your `master` then rebasing that one, to preserve your master in case it goes wrong. Then make a new pull request from your `develop` to my `master`.

**Comment by Falconne** [comment]
If you can't, don't worry about it, I can do it from my end.

**Comment by alextd** [comment]
Yea I settled merge conflicts, I should be fine on my end (github needs chat rooms, heh)

though if I see a rebase next time I can handle that

**Comment by Falconne** [comment]
Is there a reason the "counting in inventory" functionality in `RecipeWorkerCounter_CountProducts_Detour` was added to the Postfix instead of being part of the Prefix? There doesn't seem to be to me; I can move it, but just wanted to check whether there was reason you wanted it there.

**Comment by alextd** [comment]
https://github.com/Falconne/ImprovedWorkbenches/commit/f7a88f5433824333965ac16aeecbd37100e19b6d

I am on mobile now but that commit message should clear it up

**Comment by Falconne** [comment]
Oh ok. Did that cause the count for resources to be wrong though? Why does having the `statFilterWrapper.ShouldCheckInventory()` clause in the same method cause the count to be wrong for resource products?

**Comment by alextd** [comment]
The game only counts resources in stockpiles.

If no counting stockpiles are set, ImprovedWorkbenches code checks all items on the map. 

which is why it checked isThingAResource && !UsesCountingStockpile. The game can handle it in that case. If it didn't need to count a specific counting stockpile, it would not continue. 

But since it also continued with CountInventory, it would not have any counting stockpile to filter, and would check the whole map.

**Comment by Falconne** [comment]
Oh yeah I forgot about that. Been ages since I looked at this code.

I can still combine it into one method if I bring over the resource counting logic from the base game into the mod, but probably not worth it.

Regarding the additional extended property the pawns now have (their origin map), I assume you've tested the save and load still restores that data correctly, when the pawns are on a raid and stuff? Does it still allow this mod to be removed from a game without breaking the save?

Also, I expect that when some pawns go onto settle another colony they will still point back to their origin map. I don't expect that to be a big deal but sometime in the future someone may ask for a way to "retarget" the pawn's origin map. Can deal with that if it happens.

**Comment by alextd** [comment]
Saving/loaded worked -

I didn't check removing the mod. I have to imagine it would be fine, just a missing Comp definition

Settling another colony does reset the origin, since the colonist is presumably going to live in the new map. The original bill won't recognize them. Choosing the origin map yourself would be something, would require UI, so this is better than nothing.

**Comment by Falconne** [comment]
Ah yes, I see. It resets the pawn's origin whenever it leaves a map that is a faction base. Sweet.

There seems to be a null pointer exception when the new code is loading a save from the current released build. I can take a look at that.

**Pull request merged**
