### PR TITLE
Add Chinese Simplified translation

### PR DESCRIPTION
**Pull request by mm615657**
Note that there is a string missing in ur code that I found it at testing.
I have rebuilt project and everything works well

(Maybe i should creat another pr for that change but im too lazy do done that since it is only a small fix)

### CODE REVIEW

**Comment by mm615657** [comment]
Disclaimer:Chinese Simplified translation only,no Chinese Traditional translation included.

**Comment by duduluu** [comment]
You are not worthy to be a translator, you are thieves and robbers!

**Comment by duduluu** [comment]
@Falconne do not merge this please!

**Comment by mm615657** [comment]
I have no idea how it comes "thief" or "rob", everything is GNU licensed.Not to mention that I'm just asking for a feature merge.

I think it will counts as thief if someone using code or mod itself without noticing @Falconne

**Comment by mm615657** [comment]
Looks like I need to make a statement. Because in my opinion this is a personal attack rather than questioning the quality of my submit:

I made this translation and made this pr all by myself and nobody else is involved or given help. My obligation is limited to the part I submit, and responsible for any translation quality issue. I have nothing to do with the translation of others.It is okay for me to make this pr closed if the author of this project, @Falconne ,thinks there is anything inappropriate.


----
I saw an issue, I can fix it, I fixed it then I published it.I think that is how open source community works.I have no idea is there anything wrong.

**Comment by Falconne** [comment]
Don't know what that was all about. I've merged the PR, thanks for the translations. They'll be in the next update.

**Pull request merged**
