### PR TITLE
Better detour to open tab on workbench/etc selection

### PR DESCRIPTION
**Pull request by lilwhitemouse**
This should close Issue #72 .  Note that I did not build this in your routine (I'm running Linux over here), so you'll have to handle releasing on your own :)

### CODE REVIEW

**Comment by Falconne** [comment]
I'll review and merge this after finishing updating my other mods to 1.1.

**Comment by Falconne** [comment]
Published now, thanks. I refactored the code a bit to fit my coding style, let me know if you get any issues.

**Comment by lilwhitemouse** [comment]
Goodness, I just realized my code looks  a lot less _dense_ when it's on a black background ;)  Looking forward to using this!

**Comment by lilwhitemouse** [comment]
Goodness, I just realized my code looks  a lot less _dense_ when it's on a black background ;)  Looking forward to using this!

**Pull request merged**
